### ISSUE TITLE
utils module

### ISSUE THREAD

**Issue by GodefroyClair** [davidADSP/GDL_code#2]
Hi,
I'm trying to execute the notebooks as I am reading the book on O'Reilly platform but the ```utils``` folder (which correspond to a module used in chapter 3) is empty.
Is it too early to try execute the notebooks?
Thanks.

**Comment by davidADSP** [comment]
Thanks @GodefroyClair - this is fixed now

**Comment by GodefroyClair** [comment]
Hi David,

Thank you for the notice.
For your information, I've also put some feedback about the code on the
ebook on the safari (actually ex-safari) platform. I think it's public but
I don't know if and how you can access it.

**Comment by davidADSP** [comment]
Great thanks - I can't seem to see it so would you mind sending me a link?
