### ISSUE TITLE
some tiny issues in GAN 

### ISSUE THREAD

**Issue by ivanjacobs** [davidADSP/GDL_code#4]
Hey great read and great code.
I stumbled on some tiny issues when running the GAN:
in def train_discriminator
the:
```
else:
            idx = np.random.randint(0, x_train.shape[0], batch_size)
            true_imgs = x_train[idx]

```
should be
```  
else:
           idx = np.random.randint(0, x_train[0].shape[0], batch_size)
            true_imgs = x_train[0][idx]
```
as it comes back with x at [0] and y at [1]
when running the train I had to use:
```
graph = tf.get_default_graph()
with graph.as_default():
     gan.train(........
```
as it was complaining about tensors not being part of the graph. that seems to be a Keras [issue](https://github.com/keras-team/keras/issues/6462).

**Comment by davidADSP** [comment]
Can you let me know which notebook you're running to see this error?

**Comment by davidADSP** [comment]
I can't replicate this error - if you let me know which notebook produces the error or link to a reproducible example, I'll reopen.
