### ISSUE TITLE
VAE Analysis - Faces dataset

### ISSUE THREAD

**Issue by Facial-Micro-ExpressionGC** [davidADSP/GDL_code#44]
ValueError: Invalid class_mode: other; expected one of: {'sparse', 'binary', 'raw', 'categorical', None, 'input', 'multi_output'}

**Comment by Facial-Micro-ExpressionGC** [comment]
solved.

**Comment by Facial-Micro-ExpressionGC** [comment]
change class_mode='raw' and it worked

**Comment by sumugit** [comment]
Thank you for your recommendation.
