### ISSUE TITLE
03_01_autoencoder_train /run/ folder issue

### ISSUE THREAD

**Issue by jungseokhong** [davidADSP/GDL_code#5]
Heelo,

I was trying to run 03_01 code.
However, I got the following error from the second cell.

# run params
SECTION = 'vae'
RUN_ID = '0001'
DATA_NAME = 'digits'
RUN_FOLDER = '/run/{}/'.format(SECTION)
RUN_FOLDER += '_'.join([RUN_ID, DATA_NAME])

if not os.path.exists(RUN_FOLDER):
    os.mkdir(RUN_FOLDER)
    os.mkdir(os.path.join(RUN_FOLDER, 'viz'))
    os.mkdir(os.path.join(RUN_FOLDER, 'images'))
    os.mkdir(os.path.join(RUN_FOLDER, 'weights'))

MODE =  'build' #'load' #

---------------------------------------------------------------------------
FileNotFoundError                         Traceback (most recent call last)
<ipython-input-4-10e6cfcdc318> in <module>
      7 
      8 if not os.path.exists(RUN_FOLDER):
----> 9     os.mkdir(RUN_FOLDER)
     10     os.mkdir(os.path.join(RUN_FOLDER, 'viz'))
     11     os.mkdir(os.path.join(RUN_FOLDER, 'images'))

FileNotFoundError: [Errno 2] No such file or directory: './run/vae/0001_digits'

**Comment by shbnm21** [comment]
I was getting similar error so I created folder named run and in that folder create another folder named vae .
that resolved the issue.
make sure to create the folder where u are saving autoencoder_train file

**Comment by davidADSP** [comment]
Thanks good catch - I'll make sure these folders are included in the repo.

They're in the dev branch now and will merge to master shortly.
