### ISSUE TITLE
DOUBT: Did not understand the concept of 'models'.

### ISSUE THREAD

**Issue by NehaKoppikar** [davidADSP/GDL_code#52]
Please note that I am not a very good programmer. I understand that my doubt might be silly to a few people. 

Why has the author made a separate file for models? [If I am not wrong, 'models' is not actually a well-known package but a file that contains a lot of other python files that contain classes we need to perform the task. Considering, I am still on Chapter 3, models' folder's AE.py file has the class Autoencoder, which has all the custom functions required to build the model].

**Comment by mmuratarat** [comment]
So you can reuse it again and again with different combinations of parameters.

**Comment by NehaKoppikar** [comment]
Thank  you
