### ISSUE TITLE
pip install -r requirements.txt gave Tensorflow version error 1.12.0 not available

### ISSUE THREAD

**Issue by josefK128** [davidADSP/GDL_code#6]
My pip (1.19.2) could not find Tensorflow 1.12.0 as specified in requirements.txt. After installing lowest version I could find (1.13.1) Tensorboard was incompatible - after several tries I was obliged to use 1.14.0 for both - the further checks in chapter1 worked fine. However will I perhaps have trouble running some of the book examples?  I don't mind the version discrepancy otherwise - just wanted to report the issue in case someone else may also run into the problem.

I am using Python 3.7.2 on Windows 10.

**Comment by davidADSP** [comment]
Thanks for raising - I'm going to start a new dev branch when I'll make the change to upgrade to tensorflow 1.14.0. Will merge into master once I'm happy all of the examples continue to run fine.

I'm also in the process of setting this all up as a docker image - stay tuned!

**Comment by josefK128** [comment]
Thanks David,
I'm looking forward to going through some of the code examples, so ifI run to any snags I could let you know if helpful - would you prefer creatingan issue or just a brief email? (assuming any difficulties even come up)

Mark






Mark Rudolph PhD.@graphics/3Di3Dmedia.orgi3Dmedia.org/spritecloud/activation@music, poetry, papers, mathematics PhD thesismarkrudolph.org@commercial music CDshttps://www.juno.co.uk/artists/Daszuhttps://www.muziekweb.nl/Link/M00000518549/POPULAR/Daszuhttps://www.dustygroove.com/item/872694/Daszu:Zone-of-Swans-Lucid-Actual-plus-1-2-Dativa@selected github software repositorieshttps://github.com/josefK128/dome2https://github.com/josefK128/metawebhttps://github.com/josefK128/metaweb-wiki/wikihttps://github.com/josefK128/blockchainhttps://github.com/josefK128/subscriptionphone: 920-264-5386skype: josefK128


 

    On Friday, August 2, 2019, 06:12:15 AM PDT, davidADSP <notifications@github.com> wrote:  
 
 
Thanks for raising - I'm going to start a new dev branch when I'll make the change to upgrade to tensorflow 1.14.0. Will merge into master once I'm happy all of the examples continue to run fine.

I'm also in the process of setting this all up as a docker image - stay tuned!
