### ISSUE TITLE
Issue with loading library keras-contrib

### ISSUE THREAD

**Issue by iamyihwa** [davidADSP/GDL_code#9]
Hello David! Thanks for the great book! 

I have ran an error when running [CycleGan notebook: 05_01_cyclegan_train.ipynb](https://github.com/davidADSP/GDL_code/blob/master/05_01_cyclegan_train.ipynb)
It is due to an error 'keras_contrib' library not found. 

So I have installed the library separately, from the [github of  keras-contrib](https://github.com/keras-team/keras-contrib) . 

```
import os
import matplotlib.pyplot as plt

from models.cycleGAN import CycleGAN
from utils.loaders import DataLoader
```

```
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-6-647ffcce73df> in <module>
      2 import matplotlib.pyplot as plt
      3 
----> 4 from models.cycleGAN import CycleGAN
      5 from utils.loaders import DataLoader

~/GAN/GDL_code/models/cycleGAN.py in <module>
      5 #have replaced above with below line on 2019 7 8
      6 #due to an error
----> 7 from keras_contrib.layers.normalization.instancenormalization import InstanceNormalization
      8 from keras.layers import Input, Dense, Reshape, Flatten, Dropout, Concatenate
      9 from keras.layers import BatchNormalization, Activation, ZeroPadding2D, Add

ModuleNotFoundError: No module named 'keras_contrib'

```

After installing the library, it seems to work okay, but need to change slightly the command 
following [this](https://github.com/keras-team/keras-contrib/issues/466)
From this :
>  from keras_contrib.layers.normalization import InstanceNormalization
To this: 
> from keras_contrib.layers.normalization.instancenormalization import InstanceNormalization

However from the notebook it still doesn't work. 
I have tried it both from the same conda environment .. 
Any ideas?

**Comment by rednafi** [comment]
I had to install the keras_contrib module independently :persevere:.
Install `keras_contrib` via:
```
sudo pip install git+https://www.github.com/keras-team/keras-contrib.git
```
I haven't yet reached the cycleGAN example yet. Do let me know if it worked for you. :ok_woman:
